tasks:
  - name: eslint
    init: npm install eslint --save-dev
  - name: server
    init: npm install --prefix server

ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - oderwat.indent-rainbow
    - jgclark.vscode-todo-highlight
